/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import CodigoFuente.FechaPrestamo;
import CodigoFuente.GestionPublicaciones;
import CodigoFuente.GestionUsuarios;
import CodigoFuente.Libros;
import CodigoFuente.Revistas;
import CodigoFuente.Proyectos;
import CodigoFuente.Publicacion;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alberto y Alin
 */
public class Administracion extends javax.swing.JFrame {
    private String ruta;    
    private final FileNameExtensionFilter filter1 = new FileNameExtensionFilter(".jpeg","jpg");
    private final FileNameExtensionFilter filter2 = new FileNameExtensionFilter(".png","png");
    private Publicacion publicacion;
    
    /**
     * Creates new form Administracion
     */
    private JFrame principal;
    public Administracion(JFrame ventana) {                
        initComponents();
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);
    }
    // Metodo para cambiar el icono de la taza de java por uno propio
    @Override
     public Image getIconImage(){
         Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));
         return retValue;     
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        Tablero1 = new javax.swing.JTabbedPane();
        AltaPublicaciones = new javax.swing.JPanel();
        ISBNLabel1 = new javax.swing.JLabel();
        texto1 = new javax.swing.JTextField();
        TituloLabel1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JTextField();
        AutoresLabel1 = new javax.swing.JLabel();
        texto3 = new javax.swing.JTextField();
        FechaPLabel1 = new javax.swing.JLabel();
        texto4 = new javax.swing.JTextField();
        MateriaLabel1 = new javax.swing.JLabel();
        texto5 = new javax.swing.JTextField();
        FotografiaLabel1 = new javax.swing.JLabel();
        Imagen1 = new javax.swing.JButton();
        variable1 = new javax.swing.JLabel();
        texto6 = new javax.swing.JTextField();
        variable2 = new javax.swing.JLabel();
        texto7 = new javax.swing.JTextField();
        variable3 = new javax.swing.JLabel();
        texto8 = new javax.swing.JTextField();
        seleccionar1 = new javax.swing.JComboBox<>();
        Registrar1 = new javax.swing.JButton();
        BajaPublicaciones = new javax.swing.JPanel();
        texto9 = new javax.swing.JTextField();
        Eliminar1 = new javax.swing.JButton();
        ISBNLabel2 = new javax.swing.JLabel();
        ModificacionPublicaciones = new javax.swing.JPanel();
        TituloLabel2 = new javax.swing.JLabel();
        texto10 = new javax.swing.JTextField();
        AutoresLabel2 = new javax.swing.JLabel();
        texto11 = new javax.swing.JTextField();
        FechaPLabel2 = new javax.swing.JLabel();
        texto12 = new javax.swing.JTextField();
        MateriaLabel2 = new javax.swing.JLabel();
        texto13 = new javax.swing.JTextField();
        FotografiaLabel2 = new javax.swing.JLabel();
        variable4 = new javax.swing.JLabel();
        texto14 = new javax.swing.JTextField();
        variable5 = new javax.swing.JLabel();
        texto15 = new javax.swing.JTextField();
        variable6 = new javax.swing.JLabel();
        texto16 = new javax.swing.JTextField();
        Modificar1 = new javax.swing.JButton();
        seleccionar3 = new javax.swing.JComboBox<>();
        Imagen2 = new javax.swing.JButton();
        texto17 = new javax.swing.JTextField();
        ISBNLabel3 = new javax.swing.JLabel();
        Comprobar1 = new javax.swing.JButton();
        ConsultarPublicaciones = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        seleccionar4 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        Consultar1 = new javax.swing.JButton();
        Anagrama = new javax.swing.JLabel();
        Ttitulo = new javax.swing.JLabel();
        Volver1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        PanelFondo.setBackground(new java.awt.Color(204, 204, 255));

        Tablero1.setBackground(new java.awt.Color(204, 204, 255));
        Tablero1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        AltaPublicaciones.setBackground(new java.awt.Color(204, 204, 255));

        ISBNLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ISBNLabel1.setText("ISBN");

        texto1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        TituloLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TituloLabel1.setText("Título");

        texto2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        AutoresLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AutoresLabel1.setText("Autores");

        texto3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        FechaPLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FechaPLabel1.setText("Fecha P.");

        texto4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        MateriaLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        MateriaLabel1.setText("Materia");

        texto5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        FotografiaLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FotografiaLabel1.setText("Fotografia");

        Imagen1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/foto.png"))); // NOI18N
        Imagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imagen1ActionPerformed(evt);
            }
        });

        variable1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        variable1.setText("Editorial");

        texto6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        variable2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        variable2.setText("Localidad");

        texto7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        variable3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        variable3.setText("Edición");

        texto8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        seleccionar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        seleccionar1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libros", "Revistas", "Proyectos" }));
        seleccionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionar1ActionPerformed(evt);
            }
        });

        Registrar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Registrar1.setText("Registrar");
        Registrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AltaPublicacionesLayout = new javax.swing.GroupLayout(AltaPublicaciones);
        AltaPublicaciones.setLayout(AltaPublicacionesLayout);
        AltaPublicacionesLayout.setHorizontalGroup(
            AltaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AltaPublicacionesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AltaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(AltaPublicacionesLayout.createSequentialGroup()
                        .addGroup(AltaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AltaPublicacionesLayout.createSequentialGroup()
                                .addComponent(MateriaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AltaPublicacionesLayout.createSequentialGroup()
                                .addGroup(AltaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AutoresLabel1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AltaPublicacionesLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(ISBNLabel1)))
                                .addGap(18, 18, 18)))
                        .addComponent(texto1)
                        .addGap(20, 20, 20)
                        .addComponent(TituloLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AltaPublicacionesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(seleccionar1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AltaPublicacionesLayout.createSequentialGroup()
                        .addGroup(AltaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AltaPublicacionesLayout.createSequentialGroup()
                                .addGroup(AltaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(texto5)
                                    .addComponent(texto3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(FechaPLabel1)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AltaPublicacionesLayout.createSequentialGroup()
                                .addGroup(AltaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(variable2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(variable3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(variable1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AltaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(texto7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(texto8, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(texto6, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)))
                        .addGroup(AltaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(texto4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Imagen1))
                        .addGap(12, 12, 12)))
                .addContainerGap(553, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AltaPublicacionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Registrar1)
                .addGap(256, 256, 256))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AltaPublicacionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(FotografiaLabel1)
                .addGap(70, 70, 70))
        );
        AltaPublicacionesLayout.setVerticalGroup(
            AltaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AltaPublicacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seleccionar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AltaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ISBNLabel1)
                    .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloLabel1)
                    .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(AltaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AutoresLabel1)
                    .addComponent(texto3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaPLabel1)
                    .addComponent(texto4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(AltaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AltaPublicacionesLayout.createSequentialGroup()
                        .addGroup(AltaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MateriaLabel1)
                            .addComponent(texto5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(AltaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(variable1)
                            .addComponent(texto6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(AltaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(variable2)
                            .addComponent(texto7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(AltaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(variable3)
                            .addComponent(texto8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AltaPublicacionesLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Imagen1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FotografiaLabel1)))
                .addGap(31, 31, 31)
                .addComponent(Registrar1)
                .addContainerGap())
        );

        Tablero1.addTab("Alta Publicaciones ", AltaPublicaciones);

        BajaPublicaciones.setBackground(new java.awt.Color(204, 204, 255));

        Eliminar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Eliminar1.setText("Eliminar");
        Eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar1ActionPerformed(evt);
            }
        });

        ISBNLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ISBNLabel2.setText("ISBN Publicación");

        javax.swing.GroupLayout BajaPublicacionesLayout = new javax.swing.GroupLayout(BajaPublicaciones);
        BajaPublicaciones.setLayout(BajaPublicacionesLayout);
        BajaPublicacionesLayout.setHorizontalGroup(
            BajaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BajaPublicacionesLayout.createSequentialGroup()
                .addGroup(BajaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BajaPublicacionesLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(Eliminar1))
                    .addGroup(BajaPublicacionesLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(texto9, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BajaPublicacionesLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(ISBNLabel2)))
                .addContainerGap(683, Short.MAX_VALUE))
        );
        BajaPublicacionesLayout.setVerticalGroup(
            BajaPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BajaPublicacionesLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(ISBNLabel2)
                .addGap(41, 41, 41)
                .addComponent(texto9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(Eliminar1)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        Tablero1.addTab("Baja Publicaciones", BajaPublicaciones);

        ModificacionPublicaciones.setBackground(new java.awt.Color(204, 204, 255));

        TituloLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TituloLabel2.setText("Título");

        texto10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        AutoresLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AutoresLabel2.setText("Autores");

        texto11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        FechaPLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FechaPLabel2.setText("Fecha P.");

        texto12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        MateriaLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        MateriaLabel2.setText("Materia");

        texto13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        FotografiaLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FotografiaLabel2.setText("Fotografia");

        variable4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        variable4.setText("Editorial");

        texto14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        variable5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        variable5.setText("Localidad");

        texto15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        variable6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        variable6.setText("Edición");

        texto16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        Modificar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Modificar1.setText("Modificar");
        Modificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar1ActionPerformed(evt);
            }
        });

        seleccionar3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        seleccionar3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libros", "Revistas", "Proyectos" }));
        seleccionar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionar3ActionPerformed(evt);
            }
        });

        Imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/foto.png"))); // NOI18N
        Imagen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imagen2ActionPerformed(evt);
            }
        });

        texto17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        ISBNLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ISBNLabel3.setText("ISBN");

        Comprobar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Comprobar1.setText("Comprobar");
        Comprobar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comprobar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModificacionPublicacionesLayout = new javax.swing.GroupLayout(ModificacionPublicaciones);
        ModificacionPublicaciones.setLayout(ModificacionPublicacionesLayout);
        ModificacionPublicacionesLayout.setHorizontalGroup(
            ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificacionPublicacionesLayout.createSequentialGroup()
                .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificacionPublicacionesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FechaPLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(texto12, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ModificacionPublicacionesLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ModificacionPublicacionesLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(seleccionar3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ModificacionPublicacionesLayout.createSequentialGroup()
                                .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(ModificacionPublicacionesLayout.createSequentialGroup()
                                            .addComponent(AutoresLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(texto11, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(ModificacionPublicacionesLayout.createSequentialGroup()
                                                .addComponent(MateriaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(35, 35, 35)
                                                .addComponent(texto13, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(ModificacionPublicacionesLayout.createSequentialGroup()
                                                    .addComponent(variable6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(texto16, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ModificacionPublicacionesLayout.createSequentialGroup()
                                                    .addComponent(variable5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(texto15, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ModificacionPublicacionesLayout.createSequentialGroup()
                                                    .addComponent(variable4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(texto14, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ModificacionPublicacionesLayout.createSequentialGroup()
                                        .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TituloLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ISBNLabel3))
                                        .addGap(49, 49, 49)
                                        .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(texto17)
                                            .addGroup(ModificacionPublicacionesLayout.createSequentialGroup()
                                                .addComponent(texto10, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(23, 23, 23)))))
                                .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificacionPublicacionesLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Modificar1)
                                            .addComponent(FotografiaLabel2))
                                        .addGap(54, 54, 54))
                                    .addGroup(ModificacionPublicacionesLayout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Comprobar1)
                                            .addComponent(Imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 545, Short.MAX_VALUE)))))))
                .addGap(23, 23, 23))
        );
        ModificacionPublicacionesLayout.setVerticalGroup(
            ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificacionPublicacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seleccionar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificacionPublicacionesLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FechaPLabel2)
                            .addComponent(texto12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificacionPublicacionesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texto17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ISBNLabel3))
                        .addGap(23, 23, 23)))
                .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificacionPublicacionesLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(Imagen2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FotografiaLabel2)
                        .addGap(41, 41, 41)
                        .addComponent(Comprobar1)
                        .addGap(56, 56, 56)
                        .addComponent(Modificar1))
                    .addGroup(ModificacionPublicacionesLayout.createSequentialGroup()
                        .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texto10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TituloLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texto11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AutoresLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texto13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MateriaLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(variable4)
                            .addComponent(texto14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texto15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(variable5))
                        .addGap(35, 35, 35)
                        .addGroup(ModificacionPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texto16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(variable6))))
                .addGap(34, 34, 34))
        );

        Tablero1.addTab("Modificaciones", ModificacionPublicaciones);

        seleccionar4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        seleccionar4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libros", "Revistas", "Proyectos" }));

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jScrollPane3.setViewportView(tabla1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seleccionar4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seleccionar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Consultar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Consultar1.setText("Consultar");
        Consultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConsultarPublicacionesLayout = new javax.swing.GroupLayout(ConsultarPublicaciones);
        ConsultarPublicaciones.setLayout(ConsultarPublicacionesLayout);
        ConsultarPublicacionesLayout.setHorizontalGroup(
            ConsultarPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultarPublicacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ConsultarPublicacionesLayout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(Consultar1)
                .addContainerGap(542, Short.MAX_VALUE))
        );
        ConsultarPublicacionesLayout.setVerticalGroup(
            ConsultarPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarPublicacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Consultar1)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        Tablero1.addTab("Consultar ", ConsultarPublicaciones);

        Anagrama.setBackground(new java.awt.Color(0, 51, 255));
        Anagrama.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Anagrama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Anagrama.setText("Biblioteca Universitaria");

        Ttitulo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Ttitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ttitulo.setText("Administración");

        Volver1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Volver1.setText("Volver");
        Volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tablero1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Volver1)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(Ttitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Anagrama)
                        .addGap(59, 59, 59))))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Volver1)
                        .addGap(47, 47, 47))
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Anagrama, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addComponent(Tablero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1126, 609));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    // Pestaña de Alta Publicaciones
    private void Registrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrar1ActionPerformed
        try{
            String isbn = texto1.getText();
            String titulo = texto2.getText();
            String autor = texto3.getText();
            String fechap = texto4.getText();
            String materia = texto5.getText();
            String var1 = texto6.getText();
            String var2 = texto7.getText();
            String var3 = texto8.getText();
            String imagen = ruta;
            FechaPrestamo fp = new FechaPrestamo(0,0,0);
            if(isbn.equals("")|| titulo.equals("")|| autor.equals("")|| fechap.equals("")|| materia.equals("")||var1.equals("")||var2.equals("")||var3.equals("")){
                JOptionPane.showMessageDialog(this,"Rellene todos los campos","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if(seleccionar1.getSelectedItem().equals("Libros")){
                Libros l = new Libros(isbn,titulo,autor,fechap,materia,imagen,false,fp,"libros",var1,var2,var3);
                GestionPublicaciones.altaPublicacion(l);   
                JOptionPane.showMessageDialog(this,"El libro ha sido registrado","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            }else if(seleccionar1.getSelectedItem().equals("Revistas")){                
                Revistas r = new Revistas(isbn,titulo,autor,fechap,materia,imagen,false,fp,"revistas",var1,Integer.parseInt(var2),Integer.parseInt(var3));
                GestionPublicaciones.altaPublicacion(r);
                JOptionPane.showMessageDialog(this,"La revista ha sido registrado","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            }else if(seleccionar1.getSelectedItem().equals("Proyectos")){               
                Proyectos p = new Proyectos(isbn,titulo,autor,fechap,materia,imagen,false,fp,"proyectos",var1,var2,Integer.parseInt(var3));
                GestionPublicaciones.altaPublicacion(p);
                JOptionPane.showMessageDialog(this,"El proyecto ha sido registrado","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Dato no válido:\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        texto1.setText("");
        texto2.setText("");
        texto3.setText("");
        texto4.setText("");
        texto5.setText("");
        texto6.setText("");
        texto7.setText("");
        texto8.setText("");       
    }//GEN-LAST:event_Registrar1ActionPerformed
    // Pestaña de Alta Publicaciones
    private void Imagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imagen1ActionPerformed
        // Pestaña de Alta Publicaciones
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(filter1);  
        fc.setFileFilter(filter2);
        int opcion = fc.showOpenDialog(this);
        if(opcion==JFileChooser.APPROVE_OPTION){             
            String ruta1 = fc.getSelectedFile().getPath();
            ruta = ruta1;                        
        }        
    }//GEN-LAST:event_Imagen1ActionPerformed
    // Pestaña de alta publicaciones
    private void seleccionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionar1ActionPerformed
        // Pestaña de alta publicaciones
        String seleccion = (String) seleccionar1.getSelectedItem();
        if(seleccion.equals("Libros")){
            variable1.setText("Editorial");
            variable2.setText("Localidad");
            variable3.setText("Edición");
        }else if(seleccion.equals("Revistas")){
            variable1.setText("Periodicidad");
            variable2.setText("Número");
            variable3.setText("Volumen");
        }else if(seleccion.equals("Proyectos")){
            variable1.setText("Tribunal");
            variable2.setText("Titulación");
            variable3.setText("Calificación");            
        }
        
    }//GEN-LAST:event_seleccionar1ActionPerformed
    // Pestaña de Baja Publicaciones
    private void Eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar1ActionPerformed
        // Pestaña de Baja publicacion
        try{            
            String isbn = texto9.getText();            
            if (isbn.equals("")){
                JOptionPane.showMessageDialog(this,"Rellene el campo","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            Publicacion p = buscarPublicacionIsbn(isbn);
            if(p!=null){
                GestionPublicaciones.bajaPublicacion(p);
                JOptionPane.showMessageDialog(this,"Publicacion dada de baja correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this,"Error: Publicacion no encontrada","Error",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Dato no válido:\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        texto9.setText("");
    }//GEN-LAST:event_Eliminar1ActionPerformed
    // Pestaña de Modificar
    private void Modificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar1ActionPerformed
        // TODO add your handling code here:
        try{ 
            String tipo = (String) seleccionar3.getSelectedItem();
            String titulo = texto10.getText();
            String fechap = texto12.getText();
            String autor = texto11.getText();            
            String materia = texto13.getText();
            String var1 = texto14.getText();
            String var2 = texto15.getText();
            String var3 = texto16.getText();
            String imagen2 = ruta;
            String isbn = texto17.getText();
            Publicacion p = buscarPublicacionIsbn(isbn);
            if(titulo.equals("")|| autor.equals("")|| fechap.equals("")|| materia.equals("")||var1.equals("")||var2.equals("")||var3.equals("")){
                JOptionPane.showMessageDialog(this,"Rellene todos los campos","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            if(tipo.equals("Libros") && p.getTipo().equals("libros")){                 
                if(GestionPublicaciones.modificaPublicacion(p, titulo, autor, fechap, materia, imagen2, var1, var2, var3)){
                    JOptionPane.showMessageDialog(this,"El libro ha sido modificado","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this,"El libro no se ha podido modificar","Error",JOptionPane.ERROR_MESSAGE);
                }                  
            }else if(tipo.equals("Revistas") && p.getTipo().equals("revistas")){
                if(GestionPublicaciones.modificaPublicacion(p, titulo, autor, fechap, materia, imagen2, var1, var2, var3)){
                    JOptionPane.showMessageDialog(this,"La revista ha sido modificada","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(this,"La revista no se ha podido modificar","Error",JOptionPane.ERROR_MESSAGE);
                }                
            }else if(tipo.equals("Proyectos") && p.getTipo().equals("proyectos")){               
                if(GestionPublicaciones.modificaPublicacion(p, titulo, autor, fechap, materia, imagen2, var1, var2, var3)){
                    JOptionPane.showMessageDialog(this,"El proyecto ha sido modificado","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this,"El proyecto no se ha podido modificar","Error",JOptionPane.ERROR_MESSAGE);
                }                
            }
            else{
                JOptionPane.showMessageDialog(this,"No corresponde el tipo con el ISBN","Error",JOptionPane.ERROR_MESSAGE);
            }                
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Dato no válido:\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
         // limpiamos
            texto10.setText("");
            texto11.setText("");
            texto12.setText("");            
            texto13.setText("");
            texto14.setText("");
            texto15.setText("");
            texto16.setText("");            
            texto17.setText("");
    }//GEN-LAST:event_Modificar1ActionPerformed
    // Pestaña de Modificar
    private void Imagen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imagen2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(filter1);        
        int opcion = fc.showOpenDialog(this);
        if(opcion==JFileChooser.APPROVE_OPTION){ 
            String archivo = fc.getSelectedFile().getName();
            String ruta1 = fc.getSelectedFile().getPath();
            ruta = ruta1;
            JOptionPane.showMessageDialog(this, "El archivo seleccionado:  "+archivo+" ","Mensaje",JOptionPane.INFORMATION_MESSAGE);            
        }
    }//GEN-LAST:event_Imagen2ActionPerformed
    // Pestaña de modificar
    private void seleccionar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionar3ActionPerformed
        // Ventana Modificar
        String seleccion = (String) seleccionar3.getSelectedItem();
        if(seleccion.equals("Libros")){
            variable4.setText("Editorial");
            variable5.setText("Localidad");
            variable6.setText("Edición");
        }else if(seleccion.equals("Revistas")){
            variable4.setText("Periodicidad");
            variable5.setText("Número");
            variable6.setText("Volumen");
        }else if(seleccion.equals("Proyectos")){
            variable4.setText("Tribunal");
            variable5.setText("Titulación");
            variable6.setText("Calificación");            
        }
    }//GEN-LAST:event_seleccionar3ActionPerformed
    // Volver 
    private void Volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver1ActionPerformed
        // TODO add your handling code here:
        dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_Volver1ActionPerformed

   // Guardar datos
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Guardamos datos siempre que cerramos una ventana
        GestionPublicaciones.guardarPublicaciones();
        GestionUsuarios.guardarUsuarios();
    }//GEN-LAST:event_formWindowClosing

    private void Comprobar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comprobar1ActionPerformed
        // Comprobar Isbn
        try{
            String isbn = texto17.getText();
            publicacion = buscarPublicacionIsbn(isbn);
            if(publicacion != null){
                texto10.setText(publicacion.getTitulo());
                texto12.setText(publicacion.getFechaPublica());
                texto11.setText(publicacion.getAutores());
                texto13.setText(publicacion.getMateria());                
                if(seleccionar3.getSelectedItem().equals("Libros") && publicacion.getTipo().equals("libros")){
                    Libros l = (Libros) publicacion;
                    texto14.setText(l.getEditorial());
                    texto15.setText(l.getLocalidad());
                    texto16.setText(l.getEdicion());
                }else if(seleccionar3.getSelectedItem().equals("Revistas") && publicacion.getTipo().equals("revistas")){
                    Revistas r = (Revistas) publicacion;
                    texto14.setText(r.getPeriocidad());
                    texto15.setText(String.valueOf(r.getVolumen()));
                    texto16.setText(String.valueOf(r.getNumero()));
                }else if(seleccionar3.getSelectedItem().equals("Proyectos") && publicacion.getTipo().equals("proyectos")){
                    Proyectos p = (Proyectos) publicacion;
                    texto14.setText(p.getTribunal());
                    texto15.setText(p.getTitulacion());
                    texto16.setText(String.valueOf(p.getCalificacion()));
                }
            }else{
                JOptionPane.showMessageDialog(this,"No exite la publicacion","Error",JOptionPane.ERROR_MESSAGE);
            }            
        }catch(Exception e){
        }
        
    }//GEN-LAST:event_Comprobar1ActionPerformed

    private void Consultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultar1ActionPerformed
        // TODO add your handling code here:
        try{
            String tipo = (String) seleccionar4.getSelectedItem();
            ArrayList<Publicacion> lib = libros();
            ArrayList<Publicacion> rev = revistas();
            ArrayList<Publicacion> pro = proyectos();
            Publicacion publicacion;
            String var1;
            String var2;
            String var3;
            String m = "";
            DefaultTableModel modelo1 = new DefaultTableModel();
            modelo1.addColumn("ISBN");
            modelo1.addColumn("TITULO");
            modelo1.addColumn("AUTOR");
            modelo1.addColumn("FECHA PUBLICACION");
            modelo1.addColumn("MATERIA");
            modelo1.addColumn("ESTADO");         
            if(tipo.equals("Libros")){
                var1 = "EDITORIAL";
                var2 = "LOCALIDAD";
                var3 = "EDICION";
                modelo1.addColumn(var1);
                modelo1.addColumn(var2);
                modelo1.addColumn(var3);
                for(int i=0;i<lib.size();i++){
                    Libros l = (Libros) lib.get(i); 
                    if(l.isAlquilado()){
                        m = "ALQUILADO";
                    }else{
                        m="NO ALQUILADO";
                    }
                    Object v1 [] = {l.getIsbn(),l.getTitulo(),l.getAutores(),l.getFechaPublica(),l.getMateria(),m,l.getEditorial(),l.getLocalidad(),l.getEdicion()}; 
                    modelo1.addRow(v1);                
            }           
                tabla1.setModel(modelo1);
         }else if(tipo.equals("Revistas")){
                var1= "PERIODICIDAD";
                var2 = "VOLUMEN";
                var3 = "NUMERO";
                modelo1.addColumn(var1);
                modelo1.addColumn(var2);
                modelo1.addColumn(var3);
                for(int i=0;i<rev.size();i++){
                    Revistas r = (Revistas) rev.get(i); 
                    if(r.isAlquilado()){
                        m = "ALQUILADO";
                    }else{
                        m="NO ALQUILADO";
                    }
                    Object v1 [] = {r.getIsbn(),r.getTitulo(),r.getAutores(),r.getFechaPublica(),r.getMateria(),m,r.getPeriocidad(),r.getVolumen(),r.getNumero()}; 
                    modelo1.addRow(v1);                
                } 
                tabla1.setModel(modelo1); 
            } else if(tipo.equals("Proyectos")){
                var1= "TRIBUNAL";
                var2 = "TITULACION";
                var3 = "CALIFICACION";
                modelo1.addColumn(var1);
                modelo1.addColumn(var2);
                modelo1.addColumn(var3);
                for(int i=0;i<pro.size();i++){
                 Proyectos p = (Proyectos) pro.get(i); 
                    if(p.isAlquilado()){
                        m = "Alquilado";
                    }else{
                        m="No alquilado";
                    }
                    Object v1 [] = {p.getIsbn(),p.getTitulo(),p.getAutores(),p.getFechaPublica(),p.getMateria(),m,p.getTribunal(),p.getTitulacion(),p.getCalificacion()}; 
                    modelo1.addRow(v1);                
                    } 
                    tabla1.setModel(modelo1); 
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"ERROR:\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Consultar1ActionPerformed
   // Metodos complementarios
    private Publicacion buscarPublicacionIsbn(String isbn){    
        /**
         * Metodo para que nos devuelva la publicacion correspondiente
         * con el isbn introducido por pantalla. En caso de no existir, 
         * nos devuelve un objeto vacio.
         */ 
        Iterator it = GestionPublicaciones.getPublicaciones().iterator();      
        while(it.hasNext()){
            Publicacion p = (Publicacion) it.next();
            if(p.getIsbn().equals(isbn)){
                return p;
            }
        }
        return null;
    }

   private ArrayList libros(){
       ArrayList<Publicacion> lib = new ArrayList();
       String tipo = "libros";
       for(int i = 0;i<GestionPublicaciones.getPublicaciones().size();i++){
           if(GestionPublicaciones.getPublicaciones().get(i).getTipo().equals("libros")){
               lib.add(GestionPublicaciones.getPublicaciones().get(i));
           }
       }
       return lib;
   }
    private ArrayList revistas(){
       ArrayList<Publicacion> rev = new ArrayList();
       String tipo = "revistas";
       for(int i = 0;i<GestionPublicaciones.getPublicaciones().size();i++){
           if(GestionPublicaciones.getPublicaciones().get(i).getTipo().equals("revistas")){
               rev.add(GestionPublicaciones.getPublicaciones().get(i));
           }
       }
       return rev;
   }
    private ArrayList proyectos(){
       ArrayList<Publicacion> pro = new ArrayList();
       String tipo = "proyectos";
       for(int i = 0;i<GestionPublicaciones.getPublicaciones().size();i++){
           if(GestionPublicaciones.getPublicaciones().get(i).getTipo().equals("proyectos")){
               pro.add(GestionPublicaciones.getPublicaciones().get(i));
           }
       }
       return pro;
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AltaPublicaciones;
    private javax.swing.JLabel Anagrama;
    private javax.swing.JLabel AutoresLabel1;
    private javax.swing.JLabel AutoresLabel2;
    private javax.swing.JPanel BajaPublicaciones;
    private javax.swing.JButton Comprobar1;
    private javax.swing.JButton Consultar1;
    private javax.swing.JPanel ConsultarPublicaciones;
    private javax.swing.JButton Eliminar1;
    private javax.swing.JLabel FechaPLabel1;
    private javax.swing.JLabel FechaPLabel2;
    private javax.swing.JLabel FotografiaLabel1;
    private javax.swing.JLabel FotografiaLabel2;
    private javax.swing.JLabel ISBNLabel1;
    private javax.swing.JLabel ISBNLabel2;
    private javax.swing.JLabel ISBNLabel3;
    private javax.swing.JButton Imagen1;
    private javax.swing.JButton Imagen2;
    private javax.swing.JLabel MateriaLabel1;
    private javax.swing.JLabel MateriaLabel2;
    private javax.swing.JPanel ModificacionPublicaciones;
    private javax.swing.JButton Modificar1;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton Registrar1;
    private javax.swing.JTabbedPane Tablero1;
    private javax.swing.JLabel TituloLabel1;
    private javax.swing.JLabel TituloLabel2;
    private javax.swing.JLabel Ttitulo;
    private javax.swing.JButton Volver1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> seleccionar1;
    private javax.swing.JComboBox<String> seleccionar3;
    private javax.swing.JComboBox<String> seleccionar4;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField texto1;
    private javax.swing.JTextField texto10;
    private javax.swing.JTextField texto11;
    private javax.swing.JTextField texto12;
    private javax.swing.JTextField texto13;
    private javax.swing.JTextField texto14;
    private javax.swing.JTextField texto15;
    private javax.swing.JTextField texto16;
    private javax.swing.JTextField texto17;
    private javax.swing.JTextField texto2;
    private javax.swing.JTextField texto3;
    private javax.swing.JTextField texto4;
    private javax.swing.JTextField texto5;
    private javax.swing.JTextField texto6;
    private javax.swing.JTextField texto7;
    private javax.swing.JTextField texto8;
    private javax.swing.JTextField texto9;
    private javax.swing.JLabel variable1;
    private javax.swing.JLabel variable2;
    private javax.swing.JLabel variable3;
    private javax.swing.JLabel variable4;
    private javax.swing.JLabel variable5;
    private javax.swing.JLabel variable6;
    // End of variables declaration//GEN-END:variables
}
