/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import CodigoFuente.GestionPublicaciones;
import CodigoFuente.GestionUsuarios;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author Alberto y Alin
 */
public class Gestion extends javax.swing.JFrame {

    /**
     * Creates new form Gestion
     */
    private JFrame principal;
    public Gestion(JFrame ventana) {
        initComponents();
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);
    }
    // Metodo para cambiar el icono de la taza de java por uno propio
    @Override
     public Image getIconImage(){
         Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));
         return retValue;     
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo1 = new javax.swing.JPanel();
        Ttitulo = new javax.swing.JLabel();
        Anagrama = new javax.swing.JLabel();
        GestionPublicaciones1 = new javax.swing.JButton();
        GestionUsuarios1 = new javax.swing.JButton();
        Volver1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        PanelFondo1.setBackground(new java.awt.Color(204, 204, 255));

        Ttitulo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Ttitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ttitulo.setText("Gestión Principal");

        Anagrama.setBackground(new java.awt.Color(0, 51, 255));
        Anagrama.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Anagrama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Anagrama.setText("Biblioteca Universitaria");

        GestionPublicaciones1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GestionPublicaciones1.setText("Gestion Publicaciones");
        GestionPublicaciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionPublicaciones1ActionPerformed(evt);
            }
        });

        GestionUsuarios1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GestionUsuarios1.setText("Gestion Usuarios");
        GestionUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionUsuarios1ActionPerformed(evt);
            }
        });

        Volver1.setText("Volver");
        Volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFondo1Layout = new javax.swing.GroupLayout(PanelFondo1);
        PanelFondo1.setLayout(PanelFondo1Layout);
        PanelFondo1Layout.setHorizontalGroup(
            PanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondo1Layout.createSequentialGroup()
                .addGroup(PanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondo1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Anagrama))
                    .addGroup(PanelFondo1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(PanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(GestionUsuarios1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                .addComponent(GestionPublicaciones1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)))
                        .addGap(0, 151, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PanelFondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Volver1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelFondo1Layout.setVerticalGroup(
            PanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Anagrama, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Ttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(GestionPublicaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(GestionUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(Volver1)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(616, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Ventana Gestion Publicaciones
    private void GestionPublicaciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionPublicaciones1ActionPerformed
        // Acceso a la gestion de publicaciones
        GestionPublicacionesI gp = new GestionPublicacionesI(this);
    }//GEN-LAST:event_GestionPublicaciones1ActionPerformed
    // Ventana Gestion Usuarios
    private void GestionUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionUsuarios1ActionPerformed
        // Acceso a la gestion de usuarios
        GestionUsuariosI gu = new GestionUsuariosI(this);
    }//GEN-LAST:event_GestionUsuarios1ActionPerformed
    // Volver
    private void Volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver1ActionPerformed
        // Volver a la pantalla anterior
        dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_Volver1ActionPerformed
    // Guardar datos
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Guardamos antes de terminar con la aplicacion
        GestionPublicaciones.guardarPublicaciones();
        GestionUsuarios.guardarUsuarios();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anagrama;
    private javax.swing.JButton GestionPublicaciones1;
    private javax.swing.JButton GestionUsuarios1;
    private javax.swing.JPanel PanelFondo1;
    private javax.swing.JLabel Ttitulo;
    private javax.swing.JButton Volver1;
    // End of variables declaration//GEN-END:variables
}
