/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import CodigoFuente.GestionPublicaciones;
import CodigoFuente.GestionUsuarios;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author Alberto y Alin
 */
public class GestionPublicacionesI extends javax.swing.JFrame {

    /**
     * Creates new form GestionPublicacionesI
     */
    private JFrame principal;
    public GestionPublicacionesI(JFrame ventana) {
        initComponents();
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);
    }
    // Metodo para cambiar el icono de la taza de java por uno propio
    @Override
     public Image getIconImage(){
         Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));
         return retValue;     
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo1 = new javax.swing.JPanel();
        Ttitulo = new javax.swing.JLabel();
        Anagrama = new javax.swing.JLabel();
        Administracion1 = new javax.swing.JButton();
        DescripcionLabel1 = new javax.swing.JLabel();
        DescripcionLabel2 = new javax.swing.JLabel();
        Servicios1 = new javax.swing.JButton();
        Volver1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        PanelFondo1.setBackground(new java.awt.Color(204, 204, 255));

        Ttitulo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Ttitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ttitulo.setText("Gestion de Biblioteca Universitaria");

        Anagrama.setBackground(new java.awt.Color(0, 51, 255));
        Anagrama.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Anagrama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Anagrama.setText("Biblioteca Universitaria");

        Administracion1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Administracion1.setText("Administracion");
        Administracion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Administracion1ActionPerformed(evt);
            }
        });

        DescripcionLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        DescripcionLabel1.setText("Administración de las publicaciones");

        DescripcionLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        DescripcionLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DescripcionLabel2.setText("Servicios de las publicaciones");

        Servicios1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Servicios1.setText("Servicios");
        Servicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Servicios1ActionPerformed(evt);
            }
        });

        Volver1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Volver1.setText("Volver");
        Volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFondo1Layout = new javax.swing.GroupLayout(PanelFondo1);
        PanelFondo1.setLayout(PanelFondo1Layout);
        PanelFondo1Layout.setHorizontalGroup(
            PanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondo1Layout.createSequentialGroup()
                .addGroup(PanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFondo1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(DescripcionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFondo1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(PanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Administracion1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(Servicios1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelFondo1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Volver1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondo1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(PanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondo1Layout.createSequentialGroup()
                        .addComponent(Anagrama)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondo1Layout.createSequentialGroup()
                        .addComponent(Ttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondo1Layout.createSequentialGroup()
                        .addComponent(DescripcionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))))
        );
        PanelFondo1Layout.setVerticalGroup(
            PanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Anagrama, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Ttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(DescripcionLabel1)
                .addGap(18, 18, 18)
                .addComponent(Administracion1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(DescripcionLabel2)
                .addGap(18, 18, 18)
                .addComponent(Servicios1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(Volver1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(616, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Ventana Administracion
    private void Administracion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Administracion1ActionPerformed
        // Ventana administracion de alta, bajas, etc.
        Administracion adms = new Administracion(this);
    }//GEN-LAST:event_Administracion1ActionPerformed
    // Ventana Servicios
    private void Servicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Servicios1ActionPerformed
        // Ventana servicios de prestamos, devoluciones y busquedas.
        Servicios ser = new Servicios(this);
    }//GEN-LAST:event_Servicios1ActionPerformed
    // Volver
    private void Volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver1ActionPerformed
        // Volver a la pantalla anterior.
        dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_Volver1ActionPerformed
    // Guardar datos
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Guardamos antes de cerrar la aplicacion
        GestionPublicaciones.guardarPublicaciones();
        GestionUsuarios.guardarUsuarios();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Administracion1;
    private javax.swing.JLabel Anagrama;
    private javax.swing.JLabel DescripcionLabel1;
    private javax.swing.JLabel DescripcionLabel2;
    private javax.swing.JPanel PanelFondo1;
    private javax.swing.JButton Servicios1;
    private javax.swing.JLabel Ttitulo;
    private javax.swing.JButton Volver1;
    // End of variables declaration//GEN-END:variables
}
